name: jgex
architectures:
  - build-on: amd64
base: core20
version: '0.87'
summary: Java Geometry Expert
description: |
  JGEX combines dynamic geometry software,
  automated geometry theorem prover and an approach for visually
  dynamic presentation of proofs.

grade: stable

confinement: strict

apps:
  jgex:
    extensions:
      - gnome-3-38
    command: bin/jgex
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
      JAVA_OPTS: -Djava.util.prefs.userRoot="$SNAP_USER_DATA"
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    plugs:
      - home
      - network
      - cups-control

parts:
  jgex:
    build-packages: [gettext, openjdk-11-jdk]
    source: https://github.com/kovzol/Java-Geometry-Expert.git
    plugin: dump
    source-type: git
    override-build: |
      JAVAC=/usr/lib/jvm/java-11-openjdk-amd64/bin/javac
      set +u # ignore unbound variables
      if [ "$https_proxy" != "" ]; then
        https_proxy_host=$(echo $https_proxy | cut -d'/' -f3 | cut -d':' -f1)
        https_proxy_port=$(echo $https_proxy | cut -d'/' -f3 | cut -d':' -f2)
        gradle_opts="-Dhttp.proxyHost=$https_proxy_host -Dhttp.proxyPort=$https_proxy_port -Dhttps.proxyHost=$https_proxy_host -Dhttps.proxyPort=$https_proxy_port -Djava.net.useSystemProxies=true"
        fi
      ./gradlew $gradle_opts installDist && \
      mkdir -p ../install/usr/share/jgex && \
      cp -a build/install/jgex/lib/*.jar ../install/usr/share/jgex && \
      mkdir -p ../install/root && \
      cp -a build/install/jgex/bin/examples ../install/root && \
      cp -a build/install/jgex/bin/help ../install/root && \
      cp -a build/install/jgex/bin/import ../install/root && \
      cp -a build/install/jgex/bin/rules ../install/root && \
      echo "#!/bin/bash" > ../install/bin/jgex && \
      echo "JGEX_WD=~/.jgex # working directory" >> ../install/bin/jgex && \
      echo "test -d \$JGEX_WD || (mkdir -p \$JGEX_WD; cd \$SNAP/root; cp -a -u * \$JGEX_WD)" >> ../install/bin/jgex && \
      echo "cd \$JGEX_WD" >> ../install/bin/jgex && \
      echo "java -cp \$SNAP/usr/share/jgex/\\* wprover.GExpert \$*" >> ../install/bin/jgex && \
      chmod 755 ../install/bin/jgex

    stage-packages:
      - bash
      - libfreetype6
      - libpng16-16
      - libpango-1.0-0
      - libxext6
      - libxrender1
      - libgtk-3-0
      - libxtst6
      - libgl1
      - libgl1-mesa-dri
      - libgtk2.0-0
      - libasound2
      - openjdk-11-jre
      - firefox
    override-prime: |
      snapcraftctl prime
      rm -f usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
      rm -fr jar assets attic data-dir gnome-platform gradle src
